version: '3'

volumes:
  nginx-conf:
  nginx-vhost:
  nginx-html:
  nginx-certs:
  nginx-htpasswd:
  ghost-db:
  ghost-content:

networks:
  proxy:
  ghost:

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginx
    restart: always
    networks:
      - proxy
    ports:
      - "80:80"
      - "443:443"
    security_opt:
      - label:type:docker_t
    volumes:
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro,z
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-htpasswd:/etc/nginx/htpasswd:ro

  docker-gen:
    container_name: docker-gen
    image: jwilder/docker-gen
    restart: always
    networks:
      - proxy
    security_opt:
      - label:type:docker_t
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro,z
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro,z
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-htpasswd:/etc/nginx/htpasswd:ro
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  nginx-ssl:
    container_name: nginx-ssl
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    networks:
      - proxy
    volumes:
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - nginx-certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: docker-gen

  ghost-db:
    container_name: ghost-db
    image: mysql:5.7
    restart: always
    networks:
      - ghost
    security_opt:
      - label:type:docker_t
    volumes:
      - ghost-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: <password>

  ghost:
    container_name: ghost
    image: ghost:1-alpine
    restart: always
    networks:
      - proxy
      - ghost
    security_opt:
      - label:type:docker_t
    volumes:
      - ghost-content:/var/lib/ghost/content
    environment:
      VIRTUAL_HOST: sub.domain.tld
      LETSENCRYPT_HOST: sub.domain.tld
      LETSENCRYPT_EMAIL: admin@domain.tld
      url: https://sub.domain.tld
      admin_url: https://sub.domain.tld
      database__client: mysql
      database__connection__host: ghost-db
      database__connection__user: root
      database__connection__password: <password>
      database__connection__database: ghost
